language: java
sudo: required
dist: trusty

before_install: script/before
install: script/install
script: script/script

matrix:
  fast_finish: false
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk11
    - jdk: openjdk-ea

notifications:
  email: false
