language: java
sudo: required
dist: trusty

before_install: script/before
install: script/install
script: script/script

matrix:
  fast_finish: false
  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='Oracle JDK 10'
      install: script/setup F 10
    - env: JDK='Oracle JDK 11'
      install: script/setup F 11 -L BCL
  allow_failures:
    - env: JDK='Oracle JDK 9'
    - env: JDK='Oracle JDK 11'

notifications:
  email: false
